#!/bin/bash

function chmodAll(){
    for FILE in "$dir_path"/*.sh; do
        /usr/bin/chmod +x "$FILE"
    done
    echo "hoi"
}

function chmodFile(){
    chmod +x "$userfile"
}

all=false
dir_path=$(pwd)

while getopts "ad:" FLAGS; do
    case "${FLAGS}" in
        a)  all=true;;
        d)  userfile=${OPTARG};;
    esac
done

if [ "$all" == true ]; then
    chmodAll
fi

if [ -n "$userfile" ]; then
    chmodFile
fi