#!/bin/bash

function chmodAll() {
    for file in "$dir_path"/*.sh; do
        if [ -f "$file" ]; then
            chmod +x "$file"
            echo "Added execute permission to $file"
        fi
    done
}

function chmodFile() {
    if [ -f "$userfile" ]; then
        chmod +x "$userfile"
        echo "Added execute permission to $userfile"
    else
        echo "File $userfile not found."
    fi
}

all=false
dir_path=$(pwd)

while getopts "ad:" FLAGS; do
    case "${FLAGS}" in
        a)  all=true;;
        d)  userfile=${OPTARG};;
    esac
done

if [ "$all" == true ]; then
    chmodAll
fi

if [ -n "$userfile" ]; then
    chmodFile
fi