#!/bin/bash

read -p "Pfad angeben: " PATH
read -p "Dateiendung eingeben: " FILEEND

for FILE in "$PATH"/*.$FILEEND; do
    echo "$FILE"
    ((count++))
done

echo -p "$count Dateien haben die Endung $FILEEND"