#!/bin/bash

while getopts c:r::h flag; do
    case "${flag}" in
        c)  createFile=${OPTARG};;
        r)  removeFile=${OPTARG};;
        h)  help=true;;
    esac
done

if [[ $help = true || -z $createFile && -z $removeFile ]]; then
    echo "###########################"
    echo "# -c 'NAME' | create file #"
    echo "# -r 'NAME' | remove file #"
    echo "###########################"
elif [ -z $createFile ]; then
    rm -rf $removeFile
elif [ -z $removeFile ]; then
    touch $createFile
fi