#!/bin/bash

mul=false
div=false
add=false
sub=false

while getopts "d:m:a:s" flag; do
    case "${flag}" in
        d)  first_num="${OPTARG}"; div=true;;
        m)  first_num="${OPTARG}"; mul=true;;
        a)  first_num="${OPTARG}"; add=true;;
        s)  first_num="${OPTARG}"; sub=true;;
    esac
done

# Shift, um die bereits verarbeiteten Optionen zu überspringen
shift $((OPTIND-1))
second_num="${1}"

if [ -z "$first_num" ] || [ -z "$second_num" ]; then
    echo "Bitte geben Sie zwei Zahlen an."
    exit 1
fi

if [ "$div" = true ]; then
    first_num=$((first_num / second_num))
fi
if [ "$mul" = true ]; then
    first_num=$((first_num * second_num))
fi
if [ "$add" = true ]; then
    first_num=$((first_num + second_num))
fi

echo "$first_num"
