#!/bin/bash

param1=$1
ergebnis=0

while getopts c:r:k:s: flag; do
    case "${FLAG}" in
        c)  count=true;;
        r)  replace=true;;
        k)  convert=true;;
        s)  search=true;;
    esac
done

if [ count = true ]; then
    ergebnis=$(wc -w < "$param1")
fi

echo $ergebnis