#!/bin/bash

param1=""
ergebnis=0
count=false
replace=false
convert=false
search=false

while getopts "crks:" flag; do
    case "${flag}" in
        c)  count=true;;
        r)  replace=true;;
        k)  convert=true;;
        s)  search=true;;
    esac
done

shift $((OPTIND-1))
param1="${1}"

if [ -z "$param1" ]; then
    echo "Bitte geben Sie einen Dateipfad an."
    exit 1
fi
if [ ! -e "$param1" ]; then
    echo "Die Datei '$param1' existiert nicht."
    exit 1
fi
if [ "$count" = true ]; then
    ergebnis=$(wc -w < "$param1")
fi

echo "$ergebnis"
