#!/bin/bash


ergebnis=0
count=false
replace=false
convert=false
search=false

while getopts "c:r:k:s:" flag; do
    case "${flag}" in
        c)  count=true;;
        r)  replace=true;;
        k)  convert=true;;
        s)  search=true;;
    esac
done


param1=${2}
param2=${3}
param3=${4}

if [ -z "$param1" ]; then
    echo "Bitte geben Sie einen Dateipfad an."
    exit 1
fi
if [ ! -e "$param1" ]; then
    echo "Die Datei '$param1' existiert nicht."
    exit 1
fi
if [ "$count" = true ]; then
    ergebnis=$(wc -w < "$param1")
fi
if [ "$replace" = true ]; then
    sed -i "s/$param2/$param3/" $param1
fi

echo "$ergebnis"
