#!/bin/bash
benutzerAnzahl=0
echo "Wie viele Benutzer willst du erstellen? (Tippe 1 um vorherige Benutzer zu löschen)"
read benutzerAnzahl

if [ $benutzerAnzahl -ne 1 ]; then
    mkdir Benutzer
    cd Benutzer
    for ((i=0; i < $benutzerAnzahl; i++)); do
        echo "Benutzer_"$i >> "Benutzer_"$i".txt" | echo "Kennwort_"$i >> "Benutzer_"$i".txt"
    done
else
    rm -r Benutzer
fi